In [1]:
import pandas as pd

In [2]:
colors=pd.Series(["Red", "Blue", "Yellow"])

In [3]:
colors

0       Red
1      Blue
2    Yellow
dtype: object

In [5]:
cars=pd.Series(["Toyota txl","Wox Wagen","BMW"])

In [6]:
car_colors=pd.DataFrame({"Make": cars, "Color": colors})

In [7]:
car_colors

         Make   Color
0  Toyota txl     Red
1   Wox Wagen    Blue
2         BMW  Yellow

In [9]:
car_sales=pd.read_csv("car-sales.csv")

In [10]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [11]:
car_sales.to_csv("car-sales-eport-1.csv")

In [12]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [13]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [14]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [15]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [30]:
car_sales.iloc[0]

Make                Toyota
Colour               White
Odometer (KM)       150043
Doors                    4
Price            $4,000.00
Name: 0, dtype: object